{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_step.TestSetup object at 0x000002A9EE857E48>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_002(self):\n>       assert False\nE       assert False\n\nscripts\\test_step.py:12: AssertionError"}, "start": 1593250632077, "stop": 1593250632078, "uuid": "81f2f437-de58-4bd1-bb71-d9b095ca751e", "historyId": "6eb862cf60b26babee124995697ebb2d", "testCaseId": "3bbb2fd51e4c2082fa0bceb48503bc13", "fullName": "scripts.test_step.TestSetup#test_002", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_step"}, {"name": "subSuite", "value": "TestSetup"}, {"name": "host", "value": "DESKTOP-B8GEBAS"}, {"name": "thread", "value": "12308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_step"}]}